name: Generate Datas

on:
  schedule:
    # Executa a cada 12 horas
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Necessário para publicar na branch 'output'

jobs:
  build:
    name: Generate Snake Contribution Graph
    runs-on: ubuntu-latest
    steps:
      # Geração da animação do gráfico de contribuições (snake)
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: anthonylimax
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Publicação na branch output
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
